server:
  port: 8080
spring:
  application:
    name: Chat_Bot_AI1


  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai_demo
    username: spring
    password: spring

  jpa:
    hibernate:
      ddl-auto: none

  ai:
    openai:
      api-key: ${KEY_API_GEMINI}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
